
/*
 * de.unkrig.doclet.cs - A doclet which generates metadata documents for a CheckStyle extension
 *
 * Copyright (c) 2014, Arno Unkrig
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the
 *       following disclaimer.
 *    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *       following disclaimer in the documentation and/or other materials provided with the distribution.
 *    3. The name of the author may not be used to endorse or promote products derived from this software without
 *       specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

package de.unkrig.doclet.cs;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.SortedMap;
import java.util.TreeMap;

import com.sun.javadoc.ClassDoc;
import com.sun.javadoc.DocErrorReporter;
import com.sun.javadoc.FieldDoc;
import com.sun.javadoc.MethodDoc;
import com.sun.javadoc.Tag;

import de.unkrig.commons.nullanalysis.Nullable;
import de.unkrig.doclet.cs.Mediawiki.Longjump;

/**
 * Produces the 'checkstyle-metadata.xml' and 'checkstyle-metadata.properties' files for ECLIPSE-CS.
 * @author Arno
 *
 */
public final
class CheckstyleMetadata {

    private CheckstyleMetadata() {}

    /**
     * Prints the 'checkstyle-metadata.xml' file.
     */
    public static void
    checkstyleMetadataXml(final Collection<ClassDoc> classDocs, final PrintWriter pw, DocErrorReporter errorReporter) {
        pw.printf(
            ""
            + "<?xml version=\"1.0\" encoding=\"UTF-8\"?>%n"
            + "<!DOCTYPE checkstyle-metadata PUBLIC%n"
            + "\"-//eclipse-cs//DTD Check Metadata 1.1//EN\"%n"
            + "\"http://eclipse-cs.sourceforge.net/dtds/checkstyle-metadata_1_1.dtd\">%n"
            + "<checkstyle-metadata>%n"
            + "%n"
            + "    <!-- This file was generated by the CS doclet; see http://cs-contrib.unkrig.de -->"
            + "%n"
        );
        for (ClassDoc classDoc : classDocs) {
            try {

                // SUPPRESS CHECKSTYLE LineLength:3
                String  ruleGroup   = DocletUtil.optionalTag(classDoc, "@cs-rule-group", errorReporter);
                String  ruleParent  = DocletUtil.optionalTag(classDoc, "@cs-rule-parent", errorReporter);
                Boolean hasSeverity = DocletUtil.optionalBooleanTag(classDoc, "@cs-rule-has-severity", errorReporter);

                if (ruleGroup == null && ruleParent == null) continue;

                pw.printf((
                    ""
                    + "%n"
                    + "    <!-- %1$s -->%n"
                    + "%n"
                    + "    <rule-group-metadata name=\"%3$s\" priority=\"999\">%n"
                    + "        <rule-metadata%n"
                    + "            internal-name=\"%2$s\"%n"
                    + "            parent=\"%4$s\"%n"
                    + (hasSeverity == null ? "" : "            hasSeverity=\"%5$s\"%n")
                    + "            name=\"%%%2$s.name\"%n"
                    + "        >%n"
                    + "            <alternative-name internal-name=\"%2$s\" />%n"
                    + "            <description>%%%2$s.desc</description>%n"
                ), classDoc.simpleTypeName(), classDoc.qualifiedName(), ruleGroup, ruleParent, hasSeverity);

                boolean isFirstProperty = true; // SUPPRESS CHECKSTYLE UsageDistance
                for (MethodDoc methodDoc : classDoc.methods()) {

                    // SUPPRESS CHECKSTYLE LineLength:6
                    String       propertyName         = DocletUtil.optionalTag(methodDoc, "@cs-property-name",                   errorReporter);
                    String       datatype             = DocletUtil.optionalTag(methodDoc, "@cs-property-datatype",               errorReporter);
                    String       defaultValue         = DocletUtil.optionalTag(methodDoc, "@cs-property-default-value",          errorReporter);
                    String       overrideDefaultValue = DocletUtil.optionalTag(methodDoc, "@cs-property-override-default-value", errorReporter);
                    final String optionProvider       = DocletUtil.optionalTag(methodDoc, "@cs-property-option-provider",        errorReporter);
                    final Tag[]  valueOptions         = methodDoc.tags("@cs-property-value-option");

                    if (
                        propertyName == null
                        && datatype == null
                        && defaultValue == null
                        && overrideDefaultValue == null
                    ) continue;

                    // Some consistency checks.
                    String methodName = methodDoc.name();
                    if (!methodName.startsWith("set")) {
                        errorReporter.printError(methodDoc.position(), "Method is not a setter");
                        continue;
                    }
                    if (!methodName.substring(3).equalsIgnoreCase(propertyName)) {
                        errorReporter.printError(methodDoc.position(), "Property name does not match method name");
                        continue;
                    }
                    if (methodDoc.parameters().length != 1) {
                        errorReporter.printError(methodDoc.position(), "Setter must have exactly one parameter");
                        continue;
                    }
                    if (optionProvider != null && valueOptions.length > 0) {
                        errorReporter.printError(
                            methodDoc.position(),
                            "@cs-property-option-provider and @cs-property-value-option are mutually exclusive"
                        );
                        continue;
                    }

                    // Generate property description.
                    if (isFirstProperty) {
                        pw.printf("%n");         // Insert one blank line before the first property description.
                        isFirstProperty = false;
                    }
                    pw.printf(
                        (
                            ""
                            + "            <property-metadata%n"
                            + "                name=\"%2$s\"%n"
                            + "                datatype=\"%3$s\"%n"
                            + (defaultValue         == null ? "" : "                default-value=\"%4$s\"%n")
                            + (overrideDefaultValue == null ? "" : "                override-default-value=\"%5$s\"%n")
                            + "            >%n"
                            + "                <description>%%%1$s.%2$s</description>%n"
                        ),
                        classDoc.qualifiedName(),
                        propertyName,
                        datatype,
                        defaultValue,
                        overrideDefaultValue
                    );
                    if (optionProvider != null) {
                        pw.printf("                <enumeration option-provider=\"%s\" />%n", optionProvider);
                    }
                    if (valueOptions.length > 0) {
                        pw.printf("                <enumeration>%n");
                        for (Tag valueOption : valueOptions) {
                            pw.printf(
                                "                    <property-value-option value=\"%s\" />%n",
                                valueOption.text()
                            );
                        }
                        pw.printf("                </enumeration>%n");
                    }
                    pw.printf("            </property-metadata>%n");
                }

                Tag[] quickfixes = classDoc.tags("@cs-quickfix-classname");
                if (quickfixes.length > 0) {
                    pw.printf("%n");
                    for (Tag quickfix : quickfixes) {
                        pw.printf("            <quickfix classname=\"%s\" />%n", quickfix.text());
                    }
                }

                for (FieldDoc fd : classDoc.fields()) {

                    String message = DocletUtil.optionalTag(fd, "@cs-message", errorReporter);
                    if (message == null) continue;

                    String messageKey = CheckstyleMetadata.getMessageKeyFromConstantValue(fd, errorReporter);
                    if (messageKey == null) continue;

                    pw.printf("            <message-key key=\"%s\" />%n", messageKey);
                }
                pw.printf((
                    ""
                    + "        </rule-metadata>%n"
                    + "    </rule-group-metadata>%n"
                ));
            } catch (Longjump l) {
                ;
            }
        }
        pw.printf("</checkstyle-metadata>%n");
    }

    /**
     * Prints the 'checkstyle-metadata.properties' file.
     */
    public static void
    checkstyleMetadataProperties(
        final Collection<ClassDoc> classDocs,
        final PrintWriter          cmp,
        DocErrorReporter           errorReporter
    ) throws IOException {

        cmp.printf(
            ""
            + "%n"
            + "# This file was generated by the CS doclet; see http://cs-contrib.unkrig.de.%n"
            + "%n"
            + "# Rule groups:%n"
        );

        SortedMap<String, String> groups = new TreeMap<String /*group*/, String /*groupName*/>();
        for (ClassDoc classDoc : classDocs) {

            try {
                String ruleGroup     = DocletUtil.optionalTag(classDoc, "@cs-rule-group", errorReporter);
                String ruleGroupName = DocletUtil.optionalTag(classDoc, "@cs-rule-group-name", errorReporter);

                if (ruleGroup == null && ruleGroupName == null) continue;

                if (ruleGroup == null) {
                    errorReporter.printError(classDoc.position(), "'@cs-rule-group' doc tag missing");
                    continue;
                }

                if (!ruleGroup.startsWith("%")) continue;

                ruleGroup = ruleGroup.substring(1);

                String standardGroupName = CheckstyleMetadata.STANDARD_GROUPS.get(ruleGroup);
                if (standardGroupName == null) {
                    if (ruleGroupName == null) {
                        errorReporter.printError(classDoc.position(), (
                            ""
                            + "'@cs-rule-group-name' missing (must be specified because '"
                            + ruleGroup
                            + "' is not one of the CheckStyle standard groups)"
                        ));
                        continue;
                    }
                } else {
                    if (ruleGroupName == null) {
                        ruleGroupName = standardGroupName;
                    } else
                    if (ruleGroupName.equals(standardGroupName)) {
                        ;
                    } else
                    {
                        errorReporter.printWarning(classDoc.position(), (
                            ""
                            + "Group name differs from CS's standard group name '"
                            + standardGroupName
                            + "' - you should fix your group name, because otherwise editors will display TWO groups"
                        ));
                    }
                }

                String existingGroupName = groups.get(ruleGroup);
                if (existingGroupName != null && !existingGroupName.equals(ruleGroupName)) {
                    errorReporter.printError(classDoc.position(), (
                        ""
                        + "You define two different names for rule group '"
                        + ruleGroup
                        + "': '"
                        + existingGroupName
                        + "' and now '"
                        + ruleGroupName
                        + "'; you cannot have two different names for the same group in one package"
                    ));
                    continue;
                }

                groups.put(ruleGroup, ruleGroupName);
            } catch (Longjump c) {
                ;
            }
        }
        for (Entry<String, String> e : groups.entrySet()) {
            cmp.printf("%-16s = %s%n", e.getKey(), e.getValue());
        }

        cmp.printf(
            ""
            + "%n"
            + "# Custom checks, in alphabetical order.%n"
        );

        for (ClassDoc classDoc : classDocs) {

            try {
                String ruleName = DocletUtil.optionalTag(classDoc, "@cs-rule-name", errorReporter);
                if (ruleName == null) continue;

                String ruleDescription = DocletUtil.commentText(classDoc);
                if (ruleDescription == null) {
                    errorReporter.printError(classDoc.position(), "Rule lacks a description");
                    throw new Longjump();
                }

                cmp.printf((
                    ""
                    + "%n"
                    + "# --------------- %1$s ---------------%n"
                    + "%n"
                    + "%2$s.name = %1$s%n"
                    + "%2$s.desc =\\%n"
                ), ruleName, classDoc.qualifiedName());

                if (classDoc.tags("@cs-quickfix-classname").length > 0) {
                    ruleDescription += String.format("%n%nQuickfixes are available for this check.");
                }

                ruleDescription = DocletUtil.javadocTextToHtml(ruleDescription, classDoc.position(), errorReporter);

                CheckstyleMetadata.printPropertyValue(ruleDescription, cmp);

                for (MethodDoc methodDoc : classDoc.methods()) {

                    String name        = DocletUtil.optionalTag(methodDoc, "@cs-property-name", errorReporter);
                    String description = DocletUtil.optionalTag(methodDoc, "@cs-property-desc", errorReporter);

                    if (name == null && description == null) continue;

                    // Get the 'property description'. This is a bit complicated because the methods 'comment text' and
                    // and the '@cs-property-desc' doc tag must both be taken into account.
                    // We also check whether there is HTML markup in the description, because ECLIPSE-CS does not
                    // support that.
                    if (description == null) {
                        description = DocletUtil.commentText(methodDoc);
                        if (description == null) {
                            errorReporter.printError(methodDoc.position(), (
                                ""
                                + "Method has neither a comment text nor a '@cs-property-text' tag; "
                                + "at least one of them must exist (and must not contain HTML markup)"
                            ));
                            continue;
                        }
                        if (CsDoclet.containsHtmlMarkup(description)) {
                            errorReporter.printWarning(methodDoc.position(), (
                                ""
                                + "The coment text appears to contain HTML markup. "
                                + "ECLIPSE-CS cannot handle HTML markup in property descriptions; "
                                + "it is therefore recommended to add a '@cs-property-desc' tag without markup"
                            ));
                        }
                    } else {
                        if (CsDoclet.containsHtmlMarkup(description)) {
                            errorReporter.printWarning(methodDoc.position(), (
                                ""
                                + "The text after the '@cs-property-desc' tag appears to contain HTML markup; "
                                + "ECLIPSE-CS cannot handle HTML markup in property descriptions"
                            ));
                        }
                    }

                    // Some consistency checks.
                    String methodName = methodDoc.name();
                    if (!methodName.startsWith("set")) {
                        errorReporter.printError(methodDoc.position(), "Method is not a setter");
                        continue;
                    }
                    if (!methodName.substring(3).equalsIgnoreCase(name)) {
                        errorReporter.printError(methodDoc.position(), "Property name does not match method name");
                        continue;
                    }
                    if (methodDoc.parameters().length != 1) {
                        errorReporter.printError(methodDoc.position(), "Setter must have exactly one parameter");
                        continue;
                    }

                    // Generate property description.
                    cmp.printf(
                        "%1$-68s = %2$s%n",
                        classDoc.qualifiedName() + '.' + name,
                        description
                    );
                }
            } catch (Longjump c) {
                ;
            }
        }
    }

    private static void
    printPropertyValue(String text, final PrintWriter pw) throws IOException {

        boolean isFirst = true;
        for (BufferedReader br = new BufferedReader(new StringReader(text));;) {
            String line = br.readLine();
            if (line == null) break;

            if (isFirst) {
                isFirst = false;
            } else {
                pw.println("\\n\\");
            }

            pw.print('\t');
            if (line.startsWith(" ")) pw.print('\\');
            pw.print(line);
        }

        pw.println();
    }


    /**
     * Prints the 'checkstyle-metadata.properties' file.
     */
    public static void
    messagesProperties(
        final Collection<ClassDoc> classDocs,
        final PrintWriter          mp,
        DocErrorReporter           errorReporter
    ) {

        mp.printf(
            ""
            + "%n"
            + "# This file was generated by the CS doclet; see http://cs-contrib.unkrig.de%n"
            + "%n"
            + "# Custom check messages, in alphabetical order.%n"
        );

        for (ClassDoc classDoc : classDocs) {

            try {
                String ruleName = DocletUtil.optionalTag(classDoc, "@cs-rule-name", errorReporter);
                if (ruleName == null) continue;

                mp.printf((
                    ""
                    + "%n"
                    + "# --------------- %1$s ---------------%n"
                ), ruleName);

                for (FieldDoc fd : classDoc.fields()) {

                    String message = DocletUtil.optionalTag(fd, "@cs-message", errorReporter);
                    if (message == null) continue;

                    String messageKey = CheckstyleMetadata.getMessageKeyFromConstantValue(fd, errorReporter);
                    if (messageKey == null) continue;

                    mp.printf("%1$-60s = %2$s%n", messageKey, message);
                }
            } catch (Longjump c) {
                ;
            }
        }
    }

    @Nullable private static String
    getMessageKeyFromConstantValue(FieldDoc fd, DocErrorReporter errorReporter) {

        Object o = fd.constantValue();
        if (o == null) {
            errorReporter.printError(
                fd.position(),
                "Field '" + fd.name() + "' has a '@cs-message' doc tag, but not a constant value"
            );
            return null;
        }

        if (!(o instanceof String)) {
            errorReporter.printError(
                fd.position(),
                "Constant '" + fd.name() + "' must have type 'String'"
            );
            return null;
        }

        return (String) o;
    }

    /** Maps group id to (english) group name, as defined by CheckStyle. */
    private static final Map<String, String> STANDARD_GROUPS;
    static {
        Map<String, String> m = new HashMap<String, String>();
        m.put("Annotation.group",    "Annotations");
        m.put("Javadoc.group",       "Javadoc Comments");
        m.put("Naming.group",        "Naming Conventions");
        m.put("Headers.group",       "Headers");
        m.put("Imports.group",       "Imports");
        m.put("Sizes.group",         "Size Violations");
        m.put("Whitespace.group",    "Whitespace");
        m.put("Regexp.group",        "Regexp");
        m.put("Modifiers.group",     "Modifiers");
        m.put("Blocks.group",        "Blocks");
        m.put("Coding.group",        "Coding Problems");
        m.put("Design.group",        "Class Design");
        m.put("Duplicates.group",    "Duplicates");
        m.put("Metrics.group",       "Metrics");
        m.put("Miscellaneous.group", "Miscellaneous");
        m.put("Other.group",         "Other");
        m.put("Filters.group",       "Filters");
        STANDARD_GROUPS = Collections.unmodifiableMap(m);
    }
}
